# This workflow will build a Java project with Maven
name: Java CI with Maven for PR on windows and mac

on:
    pull_request:
    
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os: [macos-latest, windows-latest]
        
        name: Build with Java 11 on ${{ matrix.os }}
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 11 on ${{ matrix.os }}
          uses: actions/setup-java@v1
          with:
            java-version: 11
        - name: Cache Maven packages
          uses: actions/cache@v2
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml, **/*.yaml') }}
            restore-keys: ${{ runner.os }}-m2-
        - name: Build with Maven
          run: mvn verify
          working-directory: github-ci-example 